# Generated by Django 2.0 on 2018-01-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180111_0955'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userpofile',
        ),
    ]
