# Generated by Django 2.0 on 2018-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('bio', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ecommerce_profile',
                'managed': False,
            },
        ),
    ]
